# Generated by Django 5.1.1 on 2024-10-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_food_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='views',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
